# Toggle

In [144]:
%%HTML
<button onclick="$('.input, .prompt, .output_stderr, .output_error, .output_result').toggle();">Toggle Code</button>

# Marhine Learning

https://www.tinymind.cn/articles/74
http://www.52nlp.cn/tag/%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0%E8%AF%BE%E7%A8%8B%E4%BD%93%E9%AA%8C

# GitHub

https://github.com/, 默认用户名和密码
YunxiLiGitHub/PythonLearning            用来学习python的

YunxiLiGitHub/MachineLearning_Python    用来学习ml的

YunxiLiGitHub/coursera-ml-py

YunxiLiGitHub/MachineLearningEx

YunxiLiGitHub/CourseraML


本地目录C:\Users\eyunxli\Documents\GitHub

# Python IDE

## Eclipse + PyDev
PyDev是一个功能强大的 Eclipse插件，使用户可用 Eclipse 来进行 Python 应用程序的开发和调试。PyDev 插件的出现方便了众多的 Python 开发人员，它提供了一些很好的功能，如：语法错误提示、源代码编辑助手、Quick Outline、Globals Browser、Hierarchy View、运行和调试等等。

1) Open ellipse

2) Help - Install New Software

3) click add

4) 输入 Name 和 Location，Name 随意，Location 为 http://pydev.org/updates ；点击OK

5) 重启eclipe

## [LiClipse](http://www.liclipse.com/)

# Jupyter Notebook

## 安装配置

### 安装Anaconda
- 程序安装在C:\MyPrograms\Anaconda3
- 要运行程序，运行start/Anaconda3(64bit)/jupyter notebook
    - 启动后，会出现窗口，复制窗口中一下类似的字串到浏览器地址栏中http://localhost:8888/?token=534756d0523a0181a236a8980f5ba4a51e3e19260b2fd6b8
    - 在浏览器中，找到想要运行的程序(浏览器的根目录是C:\Users\eyunxli)
    - 使用Edge浏览器(由于浏览器快捷键(autohotkey)的限制，Edge没有被管理，所以Esc不会最小化浏览器。其他浏览器会被最小化并隐藏)
    
    
### 使用pip安装组件
- 执行windows start/Anaconda3(64it)/Anaconda promot
- 在出现的窗口键入命令安装，例如

## NBextensions
- Notebook扩展是一些能帮助你轻松把想要的内容/功能添加进Jupyter Notebook的插件。安装扩展最好的方法是Jupyter NbExtensions Configurator，它提供了一系列标签，只需勾选相应插件就能自动载入。

### 安装
- 用conda安装：
--conda install -c conda-forge jupyter_contrib_nbextensions
    -conda install -c conda-forge jupyter_nbextensions_configurator    
- 或者用pip：
    -pip install jupyter_nbextensions_configurator jupyter_contrib_nbextensions    
    -jupyter contrib nbextension install --user
    
-jupyter nbextensions_configurator enable --user

### 标题折叠 Collapsible headings


当你在处理一个大型的 notebooks 时，这项扩展非常有用，它可以让你隐藏部分内容。

### 文档结构图 Table of Contents
目录,可以将所有的heade标题栏收集起来,只对于已经运行的markdown类型的标题有效.通过目录可以进入指定链接. 

### Split Cells Notebook
拆分笔记本中的单元格，改成相邻的模式，看起来就像分了两栏。

### Variable Inspector 变量监视
显示变量的值

### 其他

#### 通知 Notify
当你长时间运行一个任务程序的时候，程序运行结束后，此扩展功能会自动提醒你。


#### 进度条 tqdm_notebook

tqdm 是一个 Python 的进度条库，在 jupyter notebook 中则被称之为 "tqdm_notebook"。自从在 nootbook 中加入了 tqdm_notebook 扩展功能，你再也不用担心其引发的混乱问题了。


#### 插入代码 Snippets

Snippets在工具栏里加了一个下拉菜单，可以非常方便的直接插入代码段，完全不用手动敲。

%debug这个本质上也不是 notebook 的一个扩展，而是 IPython 中的一个魔法命令。
%debug 魔法命令
1. 得到了一个异常
2. 重新插入一个新的输入框，输入 %debug，然后运行它
交互式的调试方法可以打开并显示代码出现异常的语句，方便你联系前后程序查看具体情况。

%Ismagic ：在输入框中运行这个命令，列出所有可用的 IPython 魔法命令
zen mode 扩展： 隐藏菜单栏，让你更专注于代码
Execute time 扩展：显示程序块运行的时间
autoreload：在不重启 notebook 的情况下，自动载入外部文件，从而修改代码，具体操作如下：

## 放PPT

### 默认方式
一种方法是用Jupyter内置的PPT选项，依次点击菜单栏里的View → Cell Toolbar → Slideshow，之后每个单元格上面都会有一个灰色的横条，选Sub-Slide。
然后输入以下代码：

jupyter nbconvert *.ipynb --to slides --post serve  #insert your notebook name instead of *.ipynb

### RISE插件
RISE插件可以编辑执行。

1) 安装RASE
- conda install -c damianavila82 rise  
或者
- pip install RISE

2)  install the JS and CSS in the proper place
jupyter-nbextension install rise --py --sys-prefix
jupyter-nbextension enable rise --py --sys-prefix

3) 重启jupyter，就会发现RISE的插件在NBExtension中

[参见](https://dataxujing.github.io/RISE-making-slides/)

## 代码中嵌入内容

### 嵌入网页

In [27]:
#Note that http urls will not be displayed. Only https are allowed inside the Iframe
from IPython.display import IFrame
IFrame('https://en.wikipedia.org/wiki/HTTPS', width=800, height=450)

### 嵌入pdf

In [28]:
from IPython.display import IFrame
IFrame('https://arxiv.org/pdf/1406.2661.pdf', width=800, height=450)

### 嵌入文件链接

In [33]:
from IPython.display import FileLink, FileLinks
FileLink('README')

C:\Users\eyunxli\Documents\GitHub\PythonLearning\README

## MD中嵌入内容

### 嵌入图片
![Alt](https://www.example.com/image.jpg)
!(https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwi3uMqhiYngAhVGXSwKHd5QBkgQjRx6BAgBEAU&url=https%3A%2F%2Fwww.python.org%2F&psig=AOvVaw0fMvSIoZ9toytPBoPgt2qC&ust=1548510492580241)

### 嵌入链接
This is an [example link](https://google.com).

### 嵌入代码块

```
bar()
if()
    else
```

### 嵌入数学公式
可以使用LaTeX公式

创建行内公式，例如 $\Gamma(n) = (n-1)!\quad\forall n\in\mathbb N$。

或者块级公式： $$ x = \dfrac{-b \pm \sqrt{b^2 - 4ac}}{2a} $$

## Qgrid
Qgrid也是一个Jupyter的小部件，不过它主要用于数据帧，装上之后，就可以像操作Excel里的筛选功能一样，方便的处理数据。
安装方法用pip安装：pip install qgrid
jupyter nbextension enable --py --sys-prefix qgrid
(# only required if you have not enabled the ipywidgets nbextension yet)
jupyter nbextension enable --py --sys-prefix widgetsnbextension
用conda安装：# only required if you have not added conda-forge to your channels yet
conda config --add channels conda-forge
conda install qgrid

## 两种模式
编辑模式(按键 Enter 开启)，命令模式(按键 Esc 开启)
Jupyter Notebook 有两种键盘输入模式。
编辑模式，允许你往单元中键入代码或文本；这时的单元框线是绿色的。
命令模式，键盘输入运行程序命令；这时的单元框线是灰色。

命令模式 (按键 Esc 开启)
Enter: 转入编辑模式
Shift-Enter: 运行本单元，选中下个单元
Ctrl-Enter: 运行本单元
Alt-Enter: 运行本单元，在其下插入新单元
Y: 单元转入代码状态
M:单元转入markdown状态
R: 单元转入raw状态
1: 设定 1 级标题
2: 设定 2 级标题
3: 设定 3 级标题
4: 设定 4 级标题
5: 设定 5 级标题
6: 设定 6 级标题
Up: 选中上方单元
K: 选中上方单元
Down: 选中下方单元
J: 选中下方单元
Shift-K: 扩大选中上方单元
Shift-J: 扩大选中下方单元
A: 在上方插入新单元
B: 在下方插入新单元
X: 剪切选中的单元
C: 复制选中的单元
Shift-V: 粘贴到上方单元
V: 粘贴到下方单元
Z: 恢复删除的最后一个单元
D,D: 删除选中的单元
Shift-M: 合并选中的单元
Ctrl-S: 文件存盘
S: 文件存盘
L: 转换行号
O: 转换输出
Shift-O: 转换输出滚动
Esc: 关闭页面
Q: 关闭页面
H: 显示快捷键帮助
I,I: 中断Notebook内核
0,0: 重启Notebook内核
Shift: 忽略
Shift-Space: 向上滚动
Space: 向下滚动

编辑模式 ( Enter 键启动)
Tab: 代码补全或缩进
Shift-Tab: 提示
Ctrl-]: 缩进
Ctrl-[: 解除缩进
Ctrl-A: 全选
Ctrl-Z: 复原
Ctrl-Shift-Z: 再做
Ctrl-Y: 再做
Ctrl-Home: 跳到单元开头
Ctrl-Up: 跳到单元开头
Ctrl-End: 跳到单元末尾
Ctrl-Down: 跳到单元末尾
Ctrl-Left: 跳到左边一个字首
Ctrl-Right: 跳到右边一个字首
Ctrl-Backspace: 删除前面一个字
Ctrl-Delete: 删除后面一个字
Esc: 进入命令模式
Ctrl-M: 进入命令模式
Shift-Enter: 运行本单元，选中下一单元
Ctrl-Enter: 运行本单元
Alt-Enter: 运行本单元，在下面插入一单元
Ctrl-Shift--: 分割单元
Ctrl-Shift-Subtract: 分割单元
Ctrl-S: 文件存盘
Shift: 忽略
Up: 光标上移或转入上一单元
Down:光标下移或转入下一单元

## 执行shell命令
- 直接在命令之前放一个“!”，就能执行shell命令，并且可以返回shell的执行结果值

In [40]:
d = !date/T  ##dos命令获取当前日期
print(d)
type(d)  ##注意，返回值的类型不是列表

['19/01/29 ']


IPython.utils.text.SList

## 表格
可以是使用在线工具 [表格生成工具](https://www.tablesgenerator.com/markdown_tables)

或者[用 Excel 生成和管理 Markdown 表格](http://moxfive.xyz/2015/10/31/excel-markdown-table/)

asöfkaskf|asöfkaskf|asöfkaskf|asöfkaskf
-|-|-|-
lsflaksf|lsflaksf|lsflaksf|lsflaksf
askflakf|askflakf|askflakf|askflakf
askfaksfa|askfaksfa|askfaksfa|askfaksfa
kfajfsaslfk|kfajfsaslfk|kfajfsaslfk|kfajfsaslfk
asldfjalsflaslfklaskflkasfalskf|asldfjalsflaslfklaskflkasfalskf|asldfjalsflaslfklaskflkasfalskf|asldfjalsflaslfklaskflkasfalskf

# Python

## Python库
NumPy：N维数组容器。以矩阵为基础的数学计算模块，纯数学。

SciPy：基于Numpy，科学计算库，有一些高阶抽象和物理模型。比方说做个傅立叶变换，这是纯数学的，用Numpy；做个滤波器，这属于信号处理模型了，在Scipy里找。

Pandas：表格容器，提供了一套名为DataFrame的数据结构，比较契合统计分析中的表结构，并且提供了计算接口，可用Numpy或其它方式进行计算。

Matplotlib: 是一个 Python 2D 绘图库。GitHub 地址：https://github.com/matplotlib/matplotlib

更多

https://www.jianshu.com/p/b6379857e1af

https://www.leiphone.com/news/201706/SP8YmNMNi2kSbUcE.html


## 语法点

### 注释
单个#开头是单行注释;
三个单引号(''')用来开始和结束多行注释
三个双引号(""")用来开始和结束多行注释

### 代码块
Python 的代码块不使用大括号 {} 来控制类，函数以及其他逻辑判断，而是用缩进来写模块。
代码块语句必须包含相同的缩进空白数量

### 一条语句多行显示
Python语句中一般以新行作为语句的结束符。
但是可以使用斜杠（ \）将一行的语句分为多行显示，如下所示：
total = item_one + \

        item_two + \
        
        item_three

语句中包含 [], {} 或 () 括号就不需要使用多行连接符。如下实例：
days = ['Monday', 'Tuesday', 'Wednesday',
        'Thursday', 'Friday']
        

### 同一行显示多条语句
可以在同一行中使用多条语句，语句之间使用分号(;)分割

import sys; x = 'runoob'; sys.stdout.write(x + '\n')

### 引号
可以使用引号( ' )、双引号( " )、三引号( ''' 或 """ ) 来表示字符串，引号的开始与结束必须的相同类型的。

其中三引号可以由多行组成，编写多行文本（注意，三引号在句首会被当做注释）。

### [函数](https://www.jianshu.com/p/4e1e49eb72b3)

### 字符串

In [46]:
str='Runoob'
 
print(str)                 # 输出字符串
print(str + '   OK')        # 连接字符串
 
print('hello\nrunoob')      # 使用反斜杠(\)+n转义特殊字符
print(r'hello\nrunoob')     # 在字符串前面添加一个 r，表示原始字符串，不会发生转义

Runoob
Runoob   OK
hello
runoob
hello\nrunoob


## 序列
Python有6个序列的内置类型，但最常见的是列表和元组。

### 序列索引（下标）
- 索引从0开始
- 索引可以反向使用，最后一个（倒数第一个）的下标是-1

In [5]:
l = [0,1,2,3,4,5];  

print("l=", l[:])
print("l[0]=", l[0], "\tl[3]=", l[3])
print("l[-1]=", l[-1], "\tl[-2]=", l[-2], "\tl[-6]=", l[-6])  

l= [0, 1, 2, 3, 4, 5]
l[0]= 0 	l[3]= 3
l[-1]= 5 	l[-2]= 4 	l[-6]= 0


### 序列切片
- 切片的本质是索引过滤，从原始序列的所有索引中，指定某个或者某些索引
- 通常一个切片操作要提供三个参数 [start_index:  stop_index:  step]
    - start_index是切片的起始位置（包括）. start_index置为空时，表示无限制，就是说可以从所有可能位置作为开始
    - stop_index是切片的结束位置（不包括）. stop_index置为空时，表示无限制，就是说可以从所有可能位置作为结束
    - step是切片步长。step置为空时，表示step=1 
- start_index和stop_index本质上就是序列索引。序列索引的所有规则都适用。
- start_index,stop_index,step不论是正数还是负数索引还是混用都可以
- 切片操作也可以只提供两个参数[start_index:  stop_index]，此时step默认为1
- [::]和[:]都表示切片所有元素
- step取正数，表示从前向后的顺序切片。取负数，表示从后向前的顺序切片。
- step取值不影响start_index和stop_index的解读。


In [6]:
l = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]; 
print("l=",l)
print("l[1:9:1]=", l[1:9:1]) 
print("l[1:9]=", l[1:9]) 
print("l[1:9:2]=", l[1:9:2]) 

l= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
l[1:9:1]= [1, 2, 3, 4, 5, 6, 7, 8]
l[1:9]= [1, 2, 3, 4, 5, 6, 7, 8]
l[1:9:2]= [1, 3, 5, 7]


In [7]:
l = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]; 
print("l=",l)
print("l[:3]=", l[:3]) 
print("l[2:]=", l[2:]) 

l= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
l[:3]= [0, 1, 2]
l[2:]= [2, 3, 4, 5, 6, 7, 8, 9, 10]


In [8]:
l = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]; 
print("l=",l)
print("l[:]=", l[:]) 
print("l[::]=", l[::]) 

l= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
l[:]= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
l[::]= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [9]:
l = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]; 
print("l=",l)
print("l[::-1]=", l[::-1], "##[start_index: stop_index: step]，step=-1")
print("l[:-1]=", l[:-1], "##[start_index: stop_index]，step=1")

l= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
l[::-1]= [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0] ##[start_index: stop_index: step]，step=-1
l[:-1]= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] ##[start_index: stop_index]，step=1


In [11]:
l = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]; 
print("l=",l)
print("l[3::1]=", l[3::1], "\t\t##正向，开始为3，结束不限定") 
print("l[3::-1]=", l[3::-1], "\t\t\t\t##反向，开始为3，结束不限定") 
print("l[:3:1]=", l[:3:1], "\t\t\t\t##正向，结束为3，开始不限定") 
print("l[:3:-1]=", l[:3:-1], "\t\t##反向，结束为3，开始不限定") 

l= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
l[3::1]= [3, 4, 5, 6, 7, 8, 9, 10] 		##正向，开始为3，结束不限定
l[3::-1]= [3, 2, 1, 0] 				##反向，开始为3，结束不限定
l[:3:1]= [0, 1, 2] 				##正向，结束为3，开始不限定
l[:3:-1]= [10, 9, 8, 7, 6, 5, 4] 		##反向，结束为3，开始不限定


### 序列切片 vs 序列索引
- 序列切片的结果是一个新的序列，序列索引的结果是序列中的一个元素

In [52]:
l= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print("l[3:4:1]=", l[3:4:1], "\t##结果是新的列表") 
print("l[3]=", l[3], "\t##结果是一个元素") 

l[3:4:1]= [3] 	##结果是新的列表
l[3]= 3 	##结果是一个元素


### 多维序列
- 对于多维序列，使用逗号([xx,xx,xx])来分隔不同维度
- 从左向右是从高维到低维
- 要指定低纬度索引，必须先指定高纬度索引
- 纬度索引可以显式指定，也可以用切片方式获得（此时可以指定多个索引值），例如可以使用[::]或者[:]取某一维度的所有索引

In [12]:
import numpy as np 
a = np.array([[["000",  "001"],  ["010",  "011"]],[["100",  "101"],  ["110",  "111"]]])  #三维列表
print ("a=", a)
print ("\n=============\n")

print ("a[0,]", "\t\t\t(n1=0, n2和n3全部。n1使用索引，而不是切片，所以降维2维)\n", a[0,])
print ("\n=============\n")

print ("a[0,:]", "\t\t\t(n1=0, n2和n3全部。n1使用索引，而不是切片，所以降维2维)\n", a[0,:])
print ("\n=============\n")

print ("a[0,:,:]", "\t\t\t(n1=0, n2和n3全部。n1使用索引，而不是切片，所以降维2维)\n", a[0,:,:])
print ("\n=============\n")

print ("a[0:1,]", "\t\t\t(n1=0, n2和n3全部。n1使用切片，所以依旧是3维)\n", a[0:1,])
print ("\n=============\n")

print ("a[0,0,0]", "\t\t\t(n1=0, n2=0, n3=0, 。n1,n2,n3索引，二不是用切片，所以降维)\n", a[0,0,0])
print ("\n=============\n")

print ("a[0:1,0:1,0:1]", "\t\t\t(n1=0, n2=0, n3=0, 。n1,n2,n3使用切片，所以依旧是3维)\n", a[0:1,0:1,0:1])
print ("\n=============\n")


a= [[['000' '001']
  ['010' '011']]

 [['100' '101']
  ['110' '111']]]


a[0,] 			(n1=0, n2和n3全部。n1使用索引，而不是切片，所以降维2维)
 [['000' '001']
 ['010' '011']]


a[0,:] 			(n1=0, n2和n3全部。n1使用索引，而不是切片，所以降维2维)
 [['000' '001']
 ['010' '011']]


a[0,:,:] 			(n1=0, n2和n3全部。n1使用索引，而不是切片，所以降维2维)
 [['000' '001']
 ['010' '011']]


a[0:1,] 			(n1=0, n2和n3全部。n1使用切片，所以依旧是3维)
 [[['000' '001']
  ['010' '011']]]


a[0,0,0] 			(n1=0, n2=0, n3=0, 。n1,n2,n3索引，二不是用切片，所以降维)
 000


a[0:1,0:1,0:1] 			(n1=0, n2=0, n3=0, 。n1,n2,n3使用切片，所以依旧是3维)
 [[['000']]]




## 元组和列表

Python 的元组与列表类似，不同之处在于元组的元素不能修改(元组中的元素值是不允许修改的，但我们可以对元组进行连接组合)。

元组使用小括号，列表使用方括号。

列表(元组)的数据项不需要具有相同的类型

空列表l=[]

空元组t=()

元组中只包含一个元素时，需要在元素后面添加逗号，否则括号会被当作运算符使用

In [13]:
tup1 = (50, "abc", 'aded')
print(tup1)

list1 = [50, "abc", 'aded']
print(list1)

(50, 'abc', 'aded')
[50, 'abc', 'aded']


In [11]:
tup1 = (50)
print(type(tup1))     # 不加逗号，类型为整型
 
tup2 = (50,)
print(type(tup2))     # 加逗号，类型为元组

<class 'int'>
<class 'tuple'>


## 字典


字典的每个键值(key=>value)对用冒号(:)分割，每个对之间用逗号(,)分割，整个字典包括在花括号({})中 ,格式如下所示：d = {key1 : value1, key2 : value2 }

键必须是唯一的，但值则不必。

值可以取任何数据类型，但键必须是不可变的，如字符串，数字或元组。

In [29]:
dict = {'Name': 'Runoob', 'Age': 7, 'Class': 'First'}
 
print ("dict['Name']: ", dict['Name'], "\t\t#访问字典")
print ("dict['Age']: ", dict['Age'], "\t\t#访问字典")

dict['Name'] = "new name"
print ("dict['Name']: ", dict['Name'], "\t\t#修改字典")

dict['Address'] = "Street"
print ("dict['Address']: ", dict['Address'], "\t\t#增加新键值")

dict[(1,2, 3)] = (1,2, 3)
print ("dict[(1,2,3)]: ", dict[(1, 2,3)], "\t\t#元组可以作为键和值")

dict[(1,2)] = [1,2]
print ("dict[(1,2)]: ", dict[(1, 2)], "\t\t#列表只能作为值，不能作为键")

del dict['Name'] # 删除键 'Name'
print(dict)

dict.clear()     # 清空字典
print(dict)

del dict         # 删除字典

dict['Name']:  Runoob 		#访问字典
dict['Age']:  7 		#访问字典
dict['Name']:  new name 		#修改字典
dict['Address']:  Street 		#增加新键值
dict[(1,2,3)]:  (1, 2, 3) 		#元组可以作为键和值
dict[(1,2)]:  [1, 2] 		#列表只能作为值，不能作为键
{'Age': 7, 'Class': 'First', 'Address': 'Street', (1, 2, 3): (1, 2, 3), (1, 2): [1, 2]}
{}


## 集合
集合（set）是一个无序的不重复元素序列。

可以使用大括号 { } 或者 set() 函数创建集合，注意：创建一个空集合必须用 set() 而不是 { }，因为 { } 是用来创建一个空字典。

创建格式：

parame = {value01,value02,...}
或者
set(value)

In [30]:
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
print(basket)                      # 这里演示的是去重功能
print('orange' in basket)                 # 快速判断元素是否在集合内
print('crabgrass' in basket)
 
# 下面展示两个集合间的运算.
a = set('abracadabra')
b = set('alacazam')
print(a)
print(b)
print( a - b )                              # 集合a中包含而集合b中不包含的元素
print( a | b )                             # 集合a或b中包含的所有元素
print( a & b )                             # 集合a和b中都包含了的元素
print(a ^ b)                              # 不同时包含于a和b的元素

{'orange', 'banana', 'apple', 'pear'}
True
False
{'a', 'b', 'r', 'c', 'd'}
{'a', 'l', 'z', 'm', 'c'}
{'d', 'b', 'r'}
{'a', 'b', 'l', 'r', 'z', 'm', 'c', 'd'}
{'a', 'c'}
{'m', 'b', 'z', 'd', 'l', 'r'}


## 推导式
推导式comprehensions（又称解析式），可以从一个数据序列构建另一个新的数据序列的结构体。共有三种推导式：

- 列表(list)推导式
- 字典(dict)推导式
- 集合(set)推导式

### 列表推导式
- 使用[]生成list

基本格式：
variable = [out_exp_res   for   out_exp   in   input_list   if   out_exp]

variable = [out_exp_res   for   out_exp   in   input_list]

    -out_exp_res：列表生成元素表达式，可以是有返回值的函数。

    -for out_exp in input_list：迭代input_list将out_exp传入out_exp_res表达式中。

    -if out_exp：根据条件过滤哪些值可以。此条件可以省略。
    
    

- 使用()生成generator
将上述两表推导式的[]改成()，即可得到生成器。

In [35]:
#过滤掉长度小于3的字符串列表，并将剩下的转换成大写字母
names = ['Bob','Tom','alice','Jerry','Wendy','Smith'] 
print([name.upper() for name in names if len(name)>3] )

#生成间隔30分钟的时间列表序列
print(["%02d:%02d"%(h,m) for h in range(0, 24) for m in range(0, 60, 30)])

#求(x, y)，其中x是0-5之间的偶数，y是0-5之间的奇数组成的元祖列表
print([(x,y) for x in range(5) if x%2==0 for y in range(5) if y%2==1] )


#求M中3, 6, 9组成的列表
M = [[1,2,3], [4,5,6], [7,8,9]] 
print([row[2] for row in M]  )        # [3, 6, 9] 

# 或者用下面的方式 

print([M[row][2] for row in (0, 1, 2)] ) # [3, 6, 9]

#求M中斜线1, 5, 9组成的列表
M = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] 

print([M[i][i] for i in range(len(M))])   # 打印M[0][0], M[1][1], M[2][2]

#求M, N中矩阵和元素的乘积
M = [[1,2,3],[4,5,6],[7,8,9]] 
N = [[2,2,2],[3,3,3],[4,4,4]] 

print([M[row][col]*N[row][col] for row in range(3) for col in range(3)] )
print([[M[row][col]*N[row][col] for col in range(3)] for row in range(3)] )

print([[M[row][col]*N[row][col] for row in range(3)] for col in range(3)] )

#把字典中age键，按照条件赋新值
bob = {'pay': 3000, 'job': 'dev', 'age': 42, 'name': 'Bob Smith'} 
sue = {'pay': 4000, 'job': 'hdw', 'age': 45, 'name': 'Sue Jones'} 
people = [bob, sue] 
print([rec['age']+100 if rec['age'] >= 45 else rec['age'] for rec in people]) # 注意for位置 


multiples = [i for i in range(30) if i%3 == 0]
print(multiples)

def squared(x):
    return x*x
multiples = [squared(i) for i in range(30) if i%3 == 0]
print(multiples)

['ALICE', 'JERRY', 'WENDY', 'SMITH']
['00:00', '00:30', '01:00', '01:30', '02:00', '02:30', '03:00', '03:30', '04:00', '04:30', '05:00', '05:30', '06:00', '06:30', '07:00', '07:30', '08:00', '08:30', '09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '12:00', '12:30', '13:00', '13:30', '14:00', '14:30', '15:00', '15:30', '16:00', '16:30', '17:00', '17:30', '18:00', '18:30', '19:00', '19:30', '20:00', '20:30', '21:00', '21:30', '22:00', '22:30', '23:00', '23:30']
[(0, 1), (0, 3), (2, 1), (2, 3), (4, 1), (4, 3)]
[3, 6, 9]
[3, 6, 9]
[1, 5, 9]
[2, 4, 6, 12, 15, 18, 28, 32, 36]
[[2, 4, 6], [12, 15, 18], [28, 32, 36]]
[[2, 12, 28], [4, 15, 32], [6, 18, 36]]
[42, 145]
[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]
[0, 9, 36, 81, 144, 225, 324, 441, 576, 729]


In [36]:
multiples = (i for i in range(30) if i%3 == 0)
print(multiples)
print(type(multiples))

<generator object <genexpr> at 0x000001F882478840>
<class 'generator'>


### 字典推导式

字典推导和列表推导的使用类似，只不过中括号改成大括号。

基本格式：{ key_expr: value_expr for value in collection if condition }

In [37]:
#用字符串和其长度创建字典
strings = ['import','is','with','if','file','exception']
D = {key: val for val,key in enumerate(strings)}

print(D)

#大小写key合并
mcase = {'a': 10, 'b': 34, 'A': 7, 'Z': 3}

mcase_frequency = {
    k.lower(): mcase.get(k.lower(), 0) + mcase.get(k.upper(), 0)
    for k in mcase.keys()
    if k.lower() in ['a','b']
}

print(mcase_frequency)

#快速更换key和value
mcase = {'a': 10, 'b': 34}
mcase_frequency = {v: k for k, v in mcase.items()}
print(mcase_frequency)

{'import': 0, 'is': 1, 'with': 2, 'if': 3, 'file': 4, 'exception': 5}
{'a': 17, 'b': 34}
{10: 'a', 34: 'b'}


### 集合推导式
集合推导式跟列表推导式也是类似的。 唯一的区别在于它使用大括号{ }。

基本格式：{ expr for value in collection if condition }


In [24]:
#集合推导式
squared = {x**2 for x in [1, 1, 2]}
print(squared)

#用集合推导式，创建字符串长度的集合
strings = ['a','is','with','if','file','exception'] 

print({len(s) for s in strings})  # 有长度相同的会只留一个，这在实际上也非常有用 

#一个由男人列表和女人列表组成的嵌套列表，取出姓名中带有两个以上含字母e的姓名，组成列表
names = [['Tom','Billy','Jefferson','Andrew','Wesley','Steven','Joe'], ['Alice','Jill','Ana','Wendy','Jennifer','Sherry','Eva']]
tmp = [] 

# 用for循环实现
for lst in names:
    for name in lst: 
        if name.count('e') >= 2: 
            tmp.append(name)

print(tmp) 

# 用嵌套列表实现
print([name for lst in names for name in lst if name.count('e')>=2]) # 注意遍历顺序，这是实现的关键 

{1, 4}
{1, 2, 4, 9}
['Jefferson', 'Wesley', 'Steven', 'Jennifer']
['Jefferson', 'Wesley', 'Steven', 'Jennifer']


## Misc

### range() vs np.arrange()
#### range

- range(start, stop[, step])

- range(stop)

这是一个通用的函数来创建包含算术级数的列表。它最常用于for循环。参数必须是纯整数。

返回一个range对象（不是列表）

如果省略step参数，则默认为1。

如果省略start参数，则默认为0。完整的形式返回一个普通整数列表。如果步骤是肯定的，最后一个元素是小于停止的最大元素; 如果step是负数，最后一个元素是大于stop的最小元素。 


#### numpy.arange
numpy.arange([start, ]stop, [step, ]dtype=None)

与range()功能完全相同，除了：1)返回值是ndarray; 2) step可以是非整数


In [40]:
import numpy as np
print(np.array(range(10)), "\t", "range(10)")
print(np.array(range(1, 11)), "\t", "range(1, 11)")
print(np.array(range(0, 30, 5)), "\t", "range(0, 30, 5)")
print(np.array(range(0, 10, 3)), "\t", "range(0, 10, 3)")
print(np.array(range(0, -10, -1)), "\t", "range(0, -10, -1)")
print(np.array(range(0)), "\t", "range(0)")
print(np.array(range(1, 0)), "\t", "range(1, 0)")

[0 1 2 3 4 5 6 7 8 9] 	 range(10)
[ 1  2  3  4  5  6  7  8  9 10] 	 range(1, 11)
[ 0  5 10 15 20 25] 	 range(0, 30, 5)
[0 3 6 9] 	 range(0, 10, 3)
[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9] 	 range(0, -10, -1)
[] 	 range(0)
[] 	 range(1, 0)


In [46]:
import numpy as np
print(np.arange(3))
print(np.arange(3.0))
print(np.arange(3,7))
print(np.arange(3,7,0.5))

[0 1 2]
[0. 1. 2.]
[3 4 5 6]
[3.  3.5 4.  4.5 5.  5.5 6.  6.5]


# PyNum

## np.loadtxt
用于从文本加载数据。文本文件中的每一行必须含有相同的数据。
loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0)

- fname要读取的文件、文件名、或生成器。
- dtype数据类型，默认float。
- comments注释。
- delimiter分隔符，默认是空格。
- skiprows跳过前几行读取，默认是0，必须是int整型。
- usecols：要读取哪些列，0是第一列。例如，usecols = （1,4,5）将提取第2，第5和第6列。默认读取所有列。
- unpack如果为True，将分列读取。

In [17]:
import numpy as np
data = np.loadtxt("data.txt",delimiter=",",
    dtype=np.int16, skiprows=(1),usecols= (0, 1,2),unpack= False)

X = data[:,0:-1]      # X对应0到倒数第2列                  
y1 = data[:,-1]        # y对应最后一列  
m = len(y1)            # 总的数据条数
col = data.shape[1]
y2 = data[:,-1:-2:-1]        # y对应最后一列  
print(X,"\n",y1,"\n",y2,"\n")

[[1600    3]
 [2400    3]
 [1416    2]
 [3000    4]
 [1985    4]
 [1534    3]] 
 [3299 3690 2320 5399 2999 3149] 
 [[3299]
 [3690]
 [2320]
 [5399]
 [2999]
 [3149]] 



## np.shape
函数是numpy.core.fromnumeric中的函数，它的功能是查看矩阵或者数组的维数。
返回值是tuple，第i个元素表示第i维的长度

In [44]:
import numpy as np
c = np.array([[[1,1,1],[1,1,2],[1,1,3],[1,1,4]], [[1,2,1],[1,2,2],[1,2,3],[1,2,4]]])
print("c=", c)
print("\n\n")
print("c.shape=", c.shape)
print("c.shape类型是",type(c.shape))
print("c维数是",len(c.shape))
print("c第0维的长度是",c.shape[0])
print("c第1维的长度是",c.shape[1])
print("c第2维的长度是",c.shape[2]) 

c= [[[1 1 1]
  [1 1 2]
  [1 1 3]
  [1 1 4]]

 [[1 2 1]
  [1 2 2]
  [1 2 3]
  [1 2 4]]]



c.shape= (2, 4, 3)
c.shape类型是 <class 'tuple'>
c维数是 3
c第0维的长度是 2
c第1维的长度是 4
c第2维的长度是 3


## [np.reshape](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)

numpy.reshape(a, newshape, order='C')
Gives a new shape to an array without changing its data.
- a : array_like, Array to be reshaped.
- newshape : int or tuple of ints
- order : {‘C’, ‘F’, ‘A’}, optional

可以是以下语法形式  x.reshape(...)
- x.reshape(n0, n1, ...)                 #整数序列
- x.reshape(n0, n1, ..., order='C')      #整数序列
- x.reshape( (n0, n1, ...), order='C')   #元组

也可以是以下语法形式  numpy.reshape(x, ...)
- numpy.reshape(x, (n0, n1, ...))#只能是元组
- numpy.reshape(x, (n0, n1, ...), order='C')  #只能是元组


newshape是新数组每一维的长度，表示为一个整数序列或者元组。每一维的长度可以是整数，或者是-1，表示自动计算。如果生成为3维的数组，用户可以只指定两维的长度，另外一维指定为-1(此时，系统可以自动计算出此维的长度)。参数中，最多出现一个-1(否则系统报错，因为可能会有多种系统计算结果)

In [139]:
import numpy as np

res = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

res.reshape(2,6)
res.reshape(2,6, order='C')
res.reshape((2,6), order='C')

#np.reshape(res,2,6)  #syntax error
np.reshape(res,(2,6))
np.reshape(res, (2,6), order='C')

print("res  一维数组")
print(res)

print("\nres.reshape(3, -1)，转化为2维，一维长度为3，二维长度自动计算")
print(res.reshape(3, -1))

print("\nres.reshape(3, 2, -1)，转化为3维，一维长度为3，二维长度为2，三维长度自动计算")
print(res.reshape(3, 2, -1))

print("\nres.reshape(2, -1, 2)转化为3维，一维长度为2，三维长度为2，二维长度自动计算)")
print(res.reshape(2, -1, 2))


res  一维数组
[ 0  1  2  3  4  5  6  7  8  9 10 11]

res.reshape(3, -1)，转化为2维，一维长度为3，二维长度自动计算
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

res.reshape(3, 2, -1)，转化为3维，一维长度为3，二维长度为2，三维长度自动计算
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]

res.reshape(2, -1, 2)转化为3维，一维长度为2，三维长度为2，二维长度自动计算)
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


## [np.zeros](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html),[np.ones](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

构造全零，全一矩阵

np.zeros,np.ones用法完全相同

用法：zeros(shape, dtype=float, order='C')

返回：返回来一个给定形状和类型的用0填充的数组；

参数：shape:形状

            dtype:数据类型，可选参数，默认numpy.float64

            dtype类型：t ,位域,如t4代表4位

                                 b,布尔值，true or false

                                 i,整数,如i8(64位）

                                u,无符号整数，u8(64位）

                                f,浮点数，f8（64位）

                               c,浮点负数，

                                o,对象，

                               s,a，字符串，s24

                               u,unicode,u24

            order:可选参数，c代表与c语言类似，行优先；F代表列优先

In [133]:
import numpy as np
print("np.zeros(5)")
print(np.zeros(5))
print("np.zeros(5,)")
print(np.zeros(5,))
print("\nnp.zeros((1,5))")
print(np.zeros((1,5)))
print("\nnp.zeros((5,1))")
print(np.zeros((5,1)))

print("\nnp.zeros((2,3,4)))")
print(np.ones((2,3,4)))

np.zeros(5)
[0. 0. 0. 0. 0.]
np.zeros(5,)
[0. 0. 0. 0. 0.]

np.zeros((1,5))
[[0. 0. 0. 0. 0.]]

np.zeros((5,1))
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]

np.zeros((2,3,4)))
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


## [np.eye](https://docs.scipy.org/doc/numpy/reference/generated/numpy.eye.html)

构造单位矩阵

In [41]:
import numpy as np
print(np.eye(3))
print(np.eye(3,M=4))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


## np.where

numpy.where() 有两种用法：

1. np.where(condition, x, y)
满足条件(condition)，输出x，不满足输出y。 

    如果是一维数组，相当于[xv if c else yv for (c,xv,yv) in zip(condition,x,y)]


2. np.where(condition)
只有条件 (condition)，没有x和y，则输出满足条件元素的坐标 (等价于numpy.nonzero)。这里的坐标以tuple的形式给出，通常原数组有多少维，输出的tuple中就包含几个数组，分别对应符合条件元素的各维坐标。

In [11]:
import numpy as np
aa = np.arange(10)

#在以下例子中，第一个参数是数组，所以对于第二个参数和第三个参数进行了广播扩展
#实际执行为np.where([0,1,2...9],[1,1..1],[-1,-1,...-1])
#0为False，所以第一个输出-1
print(np.where(aa,1,-1))
print(np.where(aa > 5,1,-1))

#在以下例子中，所有参数都是2*3数组，所以针对数组中的每个位置分别进行where操作，并得到相应结果
np.where([[True,False, True], [True,True, False]],   [[1,2,3], [4,5,6]],   [[7,8,9], [10,11,12]])

[-1  1  1  1  1  1  1  1  1  1]
[-1 -1 -1 -1 -1 -1  1  1  1  1]


array([[ 1,  8,  3],
       [ 4,  5, 12]])

In [15]:
import numpy as np
a = np.array([2,4,6,8,10])
print(np.where(a > 5))             # 返回tuple。因为a是一维数组，所以结果只有一个元素，这个元素是个array

print(a[np.where(a > 5)])              # 等价于 a[a>5]

print(np.where([[0, 1], [1, 0]]))  # 返回tuple。因为a是二维数组，所以结果有二个元素，这两个元素都是array


########### 需要再仔细看
a = np.arange(27).reshape(3,3,3)
np.where(a > 5)

(array([2, 3, 4], dtype=int64),)
[ 6  8 10]
(array([0, 1], dtype=int64), array([1, 0], dtype=int64))


(array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       dtype=int64),
 array([2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2],
       dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
       dtype=int64))

In [2]:
%magic

In [19]:
%hist

d = !date/T  ##dos命令获取当前日期
print(d)
type(d)  ##注意，返回值的类型不是列表
%%HTML
<button onclick="$('.input, .prompt, .output_stderr, .output_error, .output_result').toggle();">Toggle Code</button>
# 单个#开头是单行注释
# 第二个注释
 
'''
三个单引号用来开始和结束多行注释
第三注释
第四注释
'''
 
"""
三个双引号用来开始和结束多行注释
第五注释
第六注释
"""
print ("Hello, Python!")
# 单个#开头是单行注释
# 第二个注释
 
'''
三个单引号用来开始和结束多行注释
第三注释
第四注释
'''
 
"""
三个双引号用来开始和结束多行注释
第五注释
第六注释
"""
print ("Hello, Python!")
l = [0,1,2,3,4,5];  

print("l=", l[:])
print("l[0]=", l[0], "\tl[3]=", l[3])
print("l[-1]=", l[-1], "\tl[-2]=", l[-2], "\tl[-6]=", l[-6])
l = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]; 
print("l=",l)
print("l[1:9:1]=", l[1:9:1]) 
print("l[1:9]=", l[1:9]) 
print("l[1:9:2]=", l[1:9:2])
l = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]; 
print("l=",l)
print("l[:3]=", l[:3]) 
print("l[2:]=", l[2:])
l = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]; 
print("l=",l)
print("l[:]=", l[:]) 
print("l[::]=", l[::])
l = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]; 
print("l=",l)
print("l[::-1]=", l[::-1], "##[start_in

In [8]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import seaborn; 
from sklearn.linear_model import LinearRegression
import pylab as pl

seaborn.set()

In [47]:
# Create some simple data
import numpy as np
np.random.seed(0)
X = np.random.random(size=(20, 1))
y = 3 * X.squeeze() + 2 + np.random.randn(20)

plt.plot(X.squeeze(), y, 'o');

NameError: name 'plt' is not defined

# test


In [50]:
    for i in range(1,2+1): 
        for j in range(i+1):
            print ("X1*", i-j, "  X2*", j)
#            temp = X1**(i-j)*(X2**j)    #矩阵直接乘相当于matlab中的点乘.*


X1* 1   X2* 0
X1* 0   X2* 1
X1* 2   X2* 0
X1* 1   X2* 1
X1* 0   X2* 2
